# coding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Subject.delete_all
subjects = Subject.create([{name: 'Matematica', img_url: 'matematica.jpg', description: "L'obiettivo è aiutare i ragazzi a riflettere su problemi analitici. Col termine matematica si designa la disciplina (ed il relativo corpo di conoscenze) che studia problemi concernenti quantità, estensioni e figure spaziali, movimenti di corpi, e tutte le strutture che permettono di trattare questi aspetti in modo generale. La matematica fa largo uso degli strumenti della logica e sviluppa le proprie conoscenze nel quadro di sistemi ipotetico-deduttivi che, a partire da definizioni rigorose e da assiomi riguardanti proprietà degli oggetti definiti (risultati da un procedimento di astrazione, come triangoli, funzioni, vettori ecc.), raggiunge nuove certezze, per mezzo delle dimostrazioni, attorno a proprietà meno intuitive degli oggetti stessi (espresse dai teoremi)."},
                           {name: 'Storia', img_url: 'storia.jpg', description: "La storia è la materia che si occupa dello studio del passato tramite l'uso di fonti, cioè di tutto ciò che, configurandosi come documento, possa trasmettere il sapere. Più precisamente, la storia è la ricerca sui fatti del passato e il tentativo di una narrazione continua e sistematica degli stessi fatti, in quanto considerati di importanza per la specie umana; i fatti vengono di norma interpretati alla luce della visione etica propria dello storico in buona fede."},
                           {name: 'Inglese', img_url: 'inglese.jpg', description: "La lingua inglese, è una lingua indoeuropea appartenente al ramo occidentale delle lingue germaniche, assieme all olandese, all alto e basso tedesco, al fiammingo e al frisone. Conserva ancora un evidente parentela col sassone continentale (dialetto del basso tedesco). Dal punto di vista del dizionario contiene molti termini di origine non germanica, e in particolare latina: si valuta in oltre il 50% l'afflusso di termini latini derivati dal francese, penetrati nel lessico inglese in buona parte grazie all'occupazione normanna nei secoli dopo il 1066 (quando i Duchi di Normandia conquistarono l'Inghilterra anglo-sassone con la Battaglia di Hastings), ma anche nel Rinascimento, per influsso del latino colto e scientifico."},
                           {name: 'Italiano', img_url: 'italiano.jpg', description: "E' importante insegnare ai ragazzi la grammatica della propria lingua madre. L'italiano è una lingua romanza, basata sul fiorentino letterario usato nel Trecento, a sua volta influenzato dal volgare siciliano illustre elaborato dalla Scuola siciliana di Jacopo da Lentini (1230-1250) e dal modello latino appartenente al gruppo italico della famiglia delle lingue indoeuropee. L'italiano è una lingua ufficiale dell'Unione europea e una delle lingue più parlate al mondo. L'italiano modello è utilizzato da circa 55 milioni di italiani su 60 milioni di abitanti, in parallelo alle varianti regionali dell'italiano, alle lingue regionali e ai dialetti. Per la maggioranza degli italiani è la lingua materna e la lingua per tutti gli scambi della vita quotidiana. L'italiano modello è inoltre la lingua di riferimento per i mezzi di comunicazione nazionali, per l'editoria e per l'amministrazione dello Stato italiano."},
                           {name: 'Trattamento testi', img_url: 'trattamento_testi.jpg', description: "Questa disciplina si pone come sintesi operativa dell'applicazione al terziario delle nuove tecnologie al terziario. che hanno determinato a tutti i livelli una diversa organizzazione del lavoro d'ufficio. Infatti, molte figure professionali che prima si avvalevano dell'ausilio di collaboratori con compiti esecutivi, tendono oggi a servirsi direttamente del computer per eseguire una serie di operazioni quali la scrittura di testi, la gestione di archivi, l'elaborazione di grafici e tabelle. In questa prospettiva si ritiene particolarmente importante far acquisire al ragioniere perito commerciale la capacità di operare sui dati, organizzandoli e rielaborandoli in modo da sfruttare tutte le potenzialità dell' ofice automation. Le finalità della disciplina, quindi, consistono nel portare l'allievo al possesso delle abilità di base necessarie per il consapevole utilizzo degli strumenti tipici dell'automazione d'ufficio, che si vanno diffondendo in modo trasversale nelle più svariate attività aziendali."},
                           {name: 'Economia aziendale', img_url: 'economia_aziendale.jpg', description: "L'economia aziendale è quella branca dell'economia che studia sia con approccio qualitativo che quantitativo, tutte le tecniche, i processi di produzione e consumazione delle imprese/aziende e l'aspetto scientifico legato alla gestione aziendale durante le sue diverse fasi."},
                           {name: 'Scienze', img_url: 'scienze.jpg', description: "Per scienza si intende un sistema di conoscenze, ottenute attraverso un'attività di ricerca prevalentemente organizzata e con procedimenti metodici e rigorosi, allo scopo di giungere ad una descrizione, verosimile, oggettiva e con carattere predittivo, della realtà e delle leggi che regolano l'occorrenza dei fenomeni. La scienza moderna si sviluppa in modo particolare a partire dalla rivoluzione scientifica del XVI secolo con l'accumulo di conoscenze nei più svariati ambiti del sapere. La storia della scienza descrive il loro sviluppo nel tempo."}])

Professor.delete_all
professors = Professor.create([{name: 'Luca', surname: 'Amaldo', img_url: 'amaldo.jpg', email: 'luca.amaldo@gmail.com', telephone: '08761234567'},
                               {name: 'Carlo', surname: 'Binetti', img_url: 'binetti.jpg', email: 'carlo.binetti@gmail.com', telephone: '02361234567'},
                               {name: 'Cristina', surname: 'Cabotto', img_url: 'cabotto.jpg', email: 'cristina.cabotto@gmail.com', telephone: '01161234567'},
                               {name: 'Guido', surname: 'Veloce', img_url: 'veloce.jpg', email: 'guido.veloce@gmail.com', telephone: '03361234567'},
                               {name: 'Insegno', surname: 'Voglio', img_url: 'voglio.jpg', email: 'insegno.voglio@gmail.com', telephone: '03261234567'},
                               {name: 'Ami', surname: 'Origa', img_url: 'origa.jpg', email: 'ami.origa@gmail.com', telephone: '73361234567'}])
            
SchoolYear.delete_all
school_years = SchoolYear.create([{id: '1', name: '1'},{id: '2', name: '2'},{id: '3', name: '3'},{id: '4', name: '4'},{id: '5', name: '5'}])

SchoolDay.delete_all
school_days = SchoolDay.create([{id: '1', name: 'Lunedì'},{id: '2', name: 'Martedì'},{id: '3', name: 'Mercoledì'},{id: '4', name: 'Giovedì'},{id: '5', name: 'Venerdì'}])
                   
Plan.delete_all
plans = Plan.create([{subject_id: subjects[0].id, school_year_id: school_years[0].id, program: "Teorica delle quattro operazioni sui numeri interi. Teoremi fondamentali sulla divisibilità dei numeri interi: sui numeri primi - Massimo comun divisore e minimo multiplo comune di due o più numeri. Teorica delle frazioni ordinarie – riduzione delle frazioni ordinarie in decimali."},
                     {subject_id: subjects[0].id, school_year_id: school_years[1].id, program: "Costanti e variabili; prenozioni sui limiti. Numeri decimali periodici e loro frazioni generatrici. Nozioni sui numeri irrazionali e sulle operazioni ad essi relative. Regola per l'estrazione della radice quadrata dai numeri interi e frazionari. Calcolo dei radicali – Esponenti frazionari. Equazione generale di secondo grado ad una incognita – Discussione delle soluzioni – Relazione tra i coefficienti e le radici della equazione – esempi di equazioni riducibili al primo e al secondo grado."},
                     {subject_id: subjects[0].id, school_year_id: school_years[2].id, program: "Sulle disuguglianza di primo e secondo grado – Problemi di massimo e minimo. Interpretazione di espressioni che si presentano sotto forma indeterminata. Frazioni continue."},
                     {subject_id: subjects[0].id, school_year_id: school_years[3].id, program: "Disposizioni, permutazioni, combinazioni. Potenza intera e positiva di un binomio. Analisi indeterminata di primo grado."},
                     {subject_id: subjects[0].id, school_year_id: school_years[4].id, program: "Sezioni del cono retto circolare e deduzioni delle loro principali proprietà. Triangolo sferico – Casi semplici di eguaglianza dei triangoli sferici. Area del fuso, del triangolo e del poligono sferici – volume dello spicchio, della piramide e del segmento sferici. Teorema di Eulero sui poliedri convessi – Poliedri regolari euclidei."},
                     {subject_id: subjects[1].id, school_year_id: school_years[0].id, program: "Culture della preistoria e civiltà protostoriche. Dal paleolitico all'uso dei metalli: forme insediative e produttive; forme di culto. Le grandi civiltà del vicino Oriente; il delinearsi del fenomeno urbano e l'invenzione della scrittura. Oriente e Occidente, migrazioni indoeuropee e contatti mediterranei Migrazioni indoeuropee. Le civiltà dell'Egeo. Frequentazioni precoloniali e colonizzazioni nel Mediterraneo. Popoli dell'Italia antica e loro culture. Città e popoli della Grecia e dell'Italia. Legislazioni, tirannidi, la società delle città stato (poleis), popoli (etnie) e leghe (koiné) nel mondo greco. Miti, culti, santuari nella vita greca. Origini di Roma e periodo della monarchia. Rapporti col mondo etrusco e con gli altri popoli d'Italia. Colonie della Magna Grecia. La Grecia classica dall'affiern7azione alla crisi della polis"},
                     {subject_id: subjects[1].id, school_year_id: school_years[1].id, program: "Organizzazione dell'impero. Evoluzione istituzionale e amministrativa del principato. Nuovi ceti emergenti nell'impero mediterraneo. Il diritto romano. Organizzazione delle province. Processi di integrazione e limiti della romanizzazione: le culture diversificate delle grandi aree provinciali. Ruolo della vita cittadina. Religioni dell'Impero. Religioni dell'Impero e fattori di trasformazione; religioni pagane della salvezza. Il giudaismo. Il cristianesimo, la sua prima diffusione, le persecuzioni. Crisi del secolo III e culture dei popoli esterni. Problemi militari, demografici, economici; dinamiche sociali e colonato. Culture dei popoli estemi nei loro rapporti col mondo romano. Contatti con le grandi civiltà dell'Estremo Oriente (India, Cina degli Han) e con l'Africa non romanizzata. Mondo tardoantico"},
                     {subject_id: subjects[1].id, school_year_id: school_years[2].id, program: "Le istituzioni politiche italiane nel XII e XIV secolo. Papato e Impero. Le monarchie nazionali. Crisi economica e demografica. Trasformazioni culturali e religione nell'Europa cristiana. Evoluzione delle strutture statali e la formazione dello stato moderno. Rinnovamento della cultura. La crisi religiosa e la Riforma. La scoperta del mondo. L'economia nel XVI secolo e la rivoluzione dei prezzi."},
                     {subject_id: subjects[1].id, school_year_id: school_years[3].id, program: "Crisi dell'assolutismo: movimenti riformatori; parlamentarismo inglese; dispotismo illuminato. Imperi coloniali: sviluppi economici e conflitti internazionali. Illuminismo. La rivoluzione americana e la formazione degli Stati Uniti. La rivoluzione francese. L'età napoleonica. La Rivoluzione Industriale"},
                     {subject_id: subjects[1].id, school_year_id: school_years[4].id, program: "Le relazioni internazionali dal 1870 al 1914. Colonialismo e imperialismo. Gli stati europei: la Germania di Bismark e l'Italia da Depretis a Giolitti. La crisi della società e del sistema politico liberale europeo. La prima guerra mondiale. La nascita dell'URRS; totalitarismo e democrazia in Europa e nel mondo. Economia europea e grande crisi. Cultura di massa e ruolo degli intellettuali"},
                     {subject_id: subjects[2].id, school_year_id: school_years[0].id, program: "Simple present. modal verbs.have to. past continuous. defining relative clauses. going to and will. first conditional. may/might. indefinite pronouns"},
                     {subject_id: subjects[2].id, school_year_id: school_years[1].id, program: "Travel and souvenirs. job applications. feelings and emotions. technology, horoscopes. present perfect. just, already, yet, how long, for, since. present perfect continuous vs present perfect. question tags. second conditional"},
                     {subject_id: subjects[2].id, school_year_id: school_years[2].id, program: "Review of modals. modals for deduction. relationships. phrasal verbs. computers. sports. illnesses and remedies. feelings and descriptive adjectives"},
                     {subject_id: subjects[2].id, school_year_id: school_years[3].id, program: "The passive. past perfect. articles. reported speech. reported questions. third conditional. review of conditionals. wish"},
                     {subject_id: subjects[2].id, school_year_id: school_years[4].id, program: "The media. newspapers. TV programs. crime. criminals. feelings. cinema and films. positive and negative adjectives. basic and strong adjectives"},
                     {subject_id: subjects[3].id, school_year_id: school_years[0].id, program: "La punteggiatura e le maiuscole. La formazione delle parole: radice, suffisso e desinenza. L'articolo e i suoi usi. Il nome e le sue proprietà. L'aggettivo e le sue funzioni. Il pronome ed il suo utilizzo. Le congiunzioni : coordinative e subordinative. Utilizzo delle congiunzioni subordinative in analisi del periodo nella formazione delle proposizioni subordinate. L'interiezione o esclamazione. L'analisi logica: struttura, analisi ed utilizzo dei ruoli logici. Il soggetto. Il predicato verbale. Il predicato nominale"},
                     {subject_id: subjects[3].id, school_year_id: school_years[1].id, program: "L'interiezione o esclamazione. La sintassi della frase semplice: l'analisi logica: struttura, analisi ed utilizzo dei ruoli logici. La sintassi della frase complessa: l'analisi del periodo: proposizioni principali, coordinate, subordinate. La tipologia delle proposizioni: forma esplicita ed implicita. I gradi della coordinazione e della subordinazione : l'albero sintattico. Le proposizioni subordinate FINALI, CAUSALI, TEMPORALI, CONCESSIVE. Ripasso dei complementi di fine, di causa, di tempo, concessivo. Le proposizioni subordinate CONDIZIONALI, DICHIARATIVE, MODALI, AVVERSATIVE. Ripasso dei complementi di modo/maniera, di vantaggio/svantaggio, di età, di stima, di prezzo, di abbondanza e privazione"},
                     {subject_id: subjects[3].id, school_year_id: school_years[2].id, program: "L'origine della letteratura medievale in lingua volgare. Il dolce stil novo : la nascita della poesia amoroso-filosofica. Quadro storico-sociale dell' Alto Medioevo : la lenta disgregazione del latino come lingua unificante. Dal sermo vulgaris alle lingue neolatine. Il basso medioevo in Italia e la prima letteratura poetica in volgare."},
                     {subject_id: subjects[3].id, school_year_id: school_years[3].id, program: "L'età umanistico rinascimentale. Dalla rivoluzione scientifica del Seicento alla celebrazione della Ragione Illuministica. Il Neoclassicismo. Ugo Foscolo : la vita e il pensiero. Il Romanticismo in Italia: Giacomo Leopardi. Romanticismo e Risorgimento: Alessandro Manzoni."},
                     {subject_id: subjects[3].id, school_year_id: school_years[4].id, program: "L'eta del realismo. Giovanni Verga. Il Decadentismo. Giovanni Pascoli. Gabriele D'Annunzio. Il promo novecento"},
                     {subject_id: subjects[4].id, school_year_id: school_years[0].id, program: "Automazione d'ufficio. Sistemi di scrittura. Organizzazione e stesura di un testo. Gestione di fogli elettronici. Gestione di archivi."},
                     {subject_id: subjects[5].id, school_year_id: school_years[0].id, program: "I fondamenti dell'attività economica. L'azienda. Lo scambio economico e l'azienda. Il credito e i relativi calcoli finanziari. I mezzi di pagamento cambiari e non cambiari."},
                     {subject_id: subjects[6].id, school_year_id: school_years[0].id, program: "Il problema della misura. La meccanica. La dinamica. Energia. Termodinamica."},
                     {subject_id: subjects[6].id, school_year_id: school_years[1].id, program: "Trasformazioni fisiche e chimiche della materia. Acidi e basi. Elettroni e sistema periodico."}])

subjects[0].professors << Professor.where("surname = 'Binetti' or surname = 'Veloce' ")
subjects[1].professors << Professor.where("surname = 'Amaldo'")
subjects[2].professors << Professor.where("surname = 'Cabotto'")
subjects[3].professors << Professor.where("surname = 'Veloce'")
subjects[4].professors << Professor.where("surname = 'Voglio' or surname = 'Origa'")
subjects[5].professors << Professor.where("surname = 'Origa'")
subjects[6].professors << Professor.where("surname = 'Amaldo' or surname = 'Cabotto'")

Structure.delete_all
structures = Structure.create([{name: 'Palestra', img_url: 'palestra.jpg', description: "La palestra è dotata di varie attrezzature per esercizi individuali e di squadra. La palestra è dotata di spogliatoi con bagni e dei seguenti materieli e strutture. campo di pallavolo regolamentare con rete regolabile; campo di basket regolamentare con 2 canestri removibili; 4 paia di spalliere sulla parete laterale; 4 pertiche e 2 funi, alternate nella disposizione, sulla parete di fondo; un quadro svedese sulla parete di fondo; 2 scale verticali; palloni da pallavolo e basket; cerchi, hula-hop, corde per saltare, birilli;"},
                               {name: 'Laboratorio di informatica', img_url: 'lab_informatica.jpg', description: "Il laboratorio ha strumenti informatici per navigazione in Internet, ricerche di materiali, pubblicazioni di siti, disegno tecnico (CAD e AutoCAD), uso didattico. Soprattutto nel primo biennio è previsto un uso esteso dei laboratori e della didattica laboratoriale per far acquisire agli studenti familiarità con gli strumenti informatici, per poterli anche utilizzare nelle attività di studio e di approfondimento delle diverse discipline negli anni successivi."},
                               {name: 'Aula conferenze', img_url: 'aula_conferenze.jpg', description: "La struttura è composta da 150 posti e ospita gli eventi più importanti organizzati dall'istituto."}])

EventType.delete_all
event_types = EventType.create([{name: 'Arte e storia', description: "Gli interventi organizzati dalla scuola in questo ambito sono sempre più numerosi. Si va dalle mostre d'arte più importanti alle recenti scoperte di reperti archeologici."},
                                {name: 'Attualità', description: "Gli eventi di questo tipo sono all'ordine del giorno, dai fatti di cronaca rilevanti alla politica rivolta ai giovani, la scuola informa i suoi studenti sugli argomenti più importanti del momento."},
                                {name: 'Scienza', description: "I cambiamenti climatici, lo spazio, la tecnologia sono solo alcuni dei temi trattati in questi eventi. La scuola invita spesso scienziati famosi per spiegare come 'funziona il mondo'."}])

Event.delete_all
events = Event.create([{name: 'Days of dinosaurs', datetime: '2014-06-03 09:00', event_type_id: event_types[0].id, structure_id: structures[0].id, participations: "All'intervento parteciperanno Marco Valenti e Massimo Brando. Marco Valenti è a capo del LIAAM (Laboratorio di Informatica Applicata all'Archeologia Medievale, Università di Siena), dirige il gruppo più avanzato in quanto a tecnologie informatiche e sue applicazioni: sono i primi a rendere pubblico tutto il materiale di scavo. È stato candidato nel 2011 all'Innovation Italy Award. Massimo Brando è uno studioso indipendente, ha creato su Facebook il frequentatissimo (ed utilissimo) gruppo 'Ceramica in Archeologia' con quasi tremila utenti, dove si chiedono pareri su frammenti di ceramica ignoti e si condividono bibliografie utili allo studioso di ogni genere archeologico.", description: "Una nuova specie di dinosauri, forse la più grande ad essere vissuta in Europa 150 milioni di anni fa, è stata scoperta in Portogallo e battezzata con il nome di Torvosaurus gurneyi. Come riportato sulla rivista scientifica statunitense Plos One, in base all’esame dei resti fossili il Torvosaurus era lungo 10 metri, carnivoro e con denti affilati come rasoi e lunghi 10 centimetri; non è in assoluto il più grande predatore conosciuto (la palma spetta a specie come il Tirannosauro) ma sicuramente uno dei più grandi carnivori terrestri del Cretaceo."},
                       {name: 'Evento europeo per i giovani', datetime: '2014-06-09 10:00', event_type_id: event_types[1].id, structure_id: structures[2].id, participations: "Parteciperanno Mimmo Europa e Franco Usa.", description: "L'evento prevede una grande varietà di discussioni e attività sull'Europa unita. I partecipanti saranno invitati a partecipare a workshop, dibattiti e altre attività legate al tema 'Idee per una Europa migliore', mentre le attività culturali e sportive si terranno al di fuori della scuola."},
                       {name: 'Informatica Day', datetime: '2014-06-01 09:00', event_type_id: event_types[2].id, structure_id: structures[1].id, participations: "All'intervento parteciperanno tutti i professori di informatica dell'istituto.", description: "Partecipa e scoprirai: I principali cambiamenti sociali, tecnologici e di business introdotti dai Big Data e dall’Internet of Things. Il valore unico di Informatica Vibe per disegnare una infrastruttura dati scalabile che spazia dal dipartimentale all’enterprise ad Hadoop, dall’on-premise al Cloud. Come fornire ai clienti/cittadini una customer experience di successo grazie alla gestione dei dati master."},
                       {name: 'Festival della Complessità', datetime: '2014-03-01 09:00', event_type_id: event_types[2].id, structure_id: structures[0].id, participations: "All'intervento parteciperanno Carlo Costa e Redmond Red.", description: "La V edizione del Festival della Complessità ha un’impostazione 'sistemica'. Il Festival stesso è una metafora della complessità. È infatti un sistema che emerge grazie al contributo di decine di Partner Promotori, che da maggio a luglio, proporranno l’approccio sistemico in decine e decine di eventi, in una ventina di scuole."}])

events[0].subjects << Subject.where("name = 'Storia' or name = 'Scienze'")
events[1].subjects << Subject.where("name = 'Italiano'")
events[2].subjects << Subject.where("name = 'Trattamento testi'")
events[3].subjects << Subject.where("name = 'Scienze'")

Course.delete_all
courses = Course.create([{name: '1A', school_year_id: school_years[0].id, location: "Piano 1, aula numero 10", books: "La matematica è con noi - Zanichelli. History - LaStoriaEditori. - Geo - Mondadori. GrammaticaItaliana - LaCarta.", extra_materials: "Per approfondimenti si può far riferimento al sito del professore Amaldo www.amaldo.it"},
                         {name: '2A', school_year_id: school_years[1].id, location: "Piano terra, aula numero 3", books: "Math - Zanichelli. Geo - Mondadori. LaStoria - Mondadori. LinguaItaliana - LaCarta.", extra_materials: "I professori consigliano l'acquisto del libro di inglese EnglishPlus e il libro di matematica Math3."},
                         {name: '3A', school_year_id: school_years[2].id, location: "Piano 2, aula numero 15", books: "Operazioni - BookEditor. MondoPlus - Zanichelli. LaVeritàStorica - LaCarta. ItaPlus - Zanichelli.", extra_materials: ""},
                         {name: '1B', school_year_id: school_years[0].id, location: "Piano 1, aula numero 9", books: "Matematicamente - Zanichelli. La Terra - Esculapio. History - LaStoriaEditori. Italiano&Grammatica - Mondadori.", extra_materials: "I professori consigliano l'acquisto del libro di italiano TuttoPlus."},
                         {name: '2B', school_year_id: school_years[1].id, location: "Piano 2, aula numero 12", books: "Results - Zanichelli. Giriamo - Mondadori. LaStoria - Mondadori. LinguaItaliana - LaCarta.", extra_materials: "La professoressa Cabotto è disponibile per lezioni di approfondimento individuali."},
                         {name: '3B', school_year_id: school_years[2].id, location: "Piano 2, aula numero 16", books: "Math3 - Zanichelli. Geo - Mondadori. History - LaStoriaEditori. LinguaItaliana - LaCarta.", extra_materials: "I professori consigliano l'acquisto del libro di inglese EnglishPlus e il libro di matematica Math3."}])
 
subjects[0].courses << Course.where("name = '1A' or name = '2A' or name = '3A' or name = '1B' or name = '2B' or name = '3B'")
subjects[1].courses << Course.where("name = '1A' or name = '2A' or name = '3A' or name = '1B' or name = '2B' or name = '3B'")
subjects[2].courses << Course.where("name = '1A' or name = '2A' or name = '3A' or name = '1B' or name = '2B' or name = '3B'")
subjects[3].courses << Course.where("name = '1A' or name = '2A' or name = '3A' or name = '1B' or name = '2B' or name = '3B'")
subjects[4].courses << Course.where("name = '1A' or name = '1B'")
subjects[5].courses << Course.where("name = '1A' or name = '1B'")
subjects[6].courses << Course.where("name = '1A' or name = '2A' or name = '1B' or name = '2B'")

Schedule.delete_all
schedules = Schedule.create([{course_id: courses[0].id, school_day_id: school_days[0].id, lessons: "8:30 - 9:30 Religione / Pia Carla 9:30 - 11:30 Educazione fisica / Canesso Luca 11:30 - 13:30 Economia aziendale / Motta Concetta"},
                             {course_id: courses[0].id, school_day_id: school_days[1].id, lessons: "8:30 - 10:30 Diritto ed economia / Motta Concetta 10:30 - 12:30 Scienze della natura / Nata Lucia 11:30 - 13:30 Scienze della materia / Mate Grazia"},
                             {course_id: courses[0].id, school_day_id: school_days[2].id, lessons: "8:30 - 11:30 Scienze della materia / Mate Grazia 11:30 - 13:30 Trattamento testi / Signa Giovanna"},
                             {course_id: courses[0].id, school_day_id: school_days[3].id, lessons: "8:30 - 9:30 Matematica / Luca Amaldo /n 9:30 - 11:30 Inglese / Canesso Luca 11:30 - 13:30 Economia aziendale / Motta Concetta"},
                             {course_id: courses[0].id, school_day_id: school_days[4].id, lessons: "8:30 - 9:30 Italiano / Pia Carla 9:30 - 11:30 Scienze della natura / Canesso Luca 11:30 - 13:30 Inglese / Cristina Cabotto"},
                             {course_id: courses[1].id, school_day_id: school_days[0].id, lessons: "8:30 - 9:30 Religione / Pia Carla 9:30 - 11:30 Educazione fisica / Canesso Luca 11:30 - 13:30 Economia aziendale / Motta Concetta"},
                             {course_id: courses[1].id, school_day_id: school_days[1].id, lessons: "8:30 - 10:30 Diritto ed economia / Motta Concetta 10:30 - 12:30 Scienze della natura / Nata Lucia 11:30 - 13:30 Scienze della materia / Mate Grazia"},
                             {course_id: courses[1].id, school_day_id: school_days[2].id, lessons: "8:30 - 11:30 Scienze della materia / Mate Grazia 11:30 - 13:30 Trattamento testi / Signa Giovanna"},
                             {course_id: courses[1].id, school_day_id: school_days[3].id, lessons: "8:30 - 9:30 Matematica / Luca Amaldo 9:30 - 11:30 Inglese / Canesso Luca 11:30 - 13:30 Economia aziendale / Motta Concetta"},
                             {course_id: courses[1].id, school_day_id: school_days[4].id, lessons: "8:30 - 9:30 Italiano / Pia Carla 9:30 - 11:30 Scienze della natura / Canesso Luca 11:30 - 13:30 Inglese / Cristina Cabotto"},
                             {course_id: courses[2].id, school_day_id: school_days[0].id, lessons: "8:30 - 9:30 Religione / Pia Carla 9:30 - 11:30 Educazione fisica / Canesso Luca 11:30 - 13:30 Economia aziendale / Motta Concetta"},
                             {course_id: courses[2].id, school_day_id: school_days[1].id, lessons: "8:30 - 10:30 Diritto ed economia / Motta Concetta 10:30 - 12:30 Scienze della natura / Nata Lucia 11:30 - 13:30 Scienze della materia / Mate Grazia"},
                             {course_id: courses[2].id, school_day_id: school_days[2].id, lessons: "8:30 - 11:30 Scienze della materia / Mate Grazia 11:30 - 13:30 Trattamento testi / Signa Giovanna"},
                             {course_id: courses[2].id, school_day_id: school_days[3].id, lessons: "8:30 - 9:30 Matematica / Luca Amaldo 9:30 - 11:30 Inglese / Canesso Luca 11:30 - 13:30 Economia aziendale / Motta Concetta"},
                             {course_id: courses[2].id, school_day_id: school_days[4].id, lessons: "8:30 - 9:30 Italiano / Pia Carla 9:30 - 11:30 Scienze della natura / Canesso Luca 11:30 - 13:30 Inglese / Cristina Cabotto"},
                             {course_id: courses[3].id, school_day_id: school_days[0].id, lessons: "8:30 - 9:30 Religione / Pia Carla 9:30 - 11:30 Educazione fisica / Canesso Luca 11:30 - 13:30 Economia aziendale / Motta Concetta"},
                             {course_id: courses[3].id, school_day_id: school_days[1].id, lessons: "8:30 - 10:30 Diritto ed economia / Motta Concetta 10:30 - 12:30 Scienze della natura / Nata Lucia 11:30 - 13:30 Scienze della materia / Mate Grazia"},
                             {course_id: courses[3].id, school_day_id: school_days[2].id, lessons: "8:30 - 11:30 Scienze della materia / Mate Grazia 11:30 - 13:30 Trattamento testi / Signa Giovanna"},
                             {course_id: courses[3].id, school_day_id: school_days[3].id, lessons: "8:30 - 9:30 Matematica / Luca Amaldo 9:30 - 11:30 Inglese / Canesso Luca /n 11:30 - 13:30 Economia aziendale / Motta Concetta"},
                             {course_id: courses[3].id, school_day_id: school_days[4].id, lessons: "8:30 - 9:30 Italiano / Pia Carla 9:30 - 11:30 Scienze della natura / Canesso Luca 11:30 - 13:30 Inglese / Cristina Cabotto"},
                             {course_id: courses[4].id, school_day_id: school_days[0].id, lessons: "8:30 - 9:30 Religione / Pia Carla 9:30 - 11:30 Educazione fisica / Canesso Luca 11:30 - 13:30 Economia aziendale / Motta Concetta"},
                             {course_id: courses[4].id, school_day_id: school_days[1].id, lessons: "8:30 - 10:30 Diritto ed economia / Motta Concetta 10:30 - 12:30 Scienze della natura / Nata Lucia 11:30 - 13:30 Scienze della materia / Mate Grazia"},
                             {course_id: courses[4].id, school_day_id: school_days[2].id, lessons: "8:30 - 11:30 Scienze della materia / Mate Grazia 11:30 - 13:30 Trattamento testi / Signa Giovanna"},
                             {course_id: courses[4].id, school_day_id: school_days[3].id, lessons: "8:30 - 9:30 Matematica / Luca Amaldo 9:30 - 11:30 Inglese / Canesso Luca 11:30 - 13:30 Economia aziendale / Motta Concetta"},
                             {course_id: courses[4].id, school_day_id: school_days[4].id, lessons: "8:30 - 9:30 Italiano / Pia Carla 9:30 - 11:30 Scienze della natura / Canesso Luca 11:30 - 13:30 Inglese / Cristina Cabotto"}])
                       
Meeting.delete_all
meetings = Meeting.create([{datetime: '2014-06-03 09:00', location: 'aula 9', course_id: courses[0].id},
                           {datetime: '2014-02-07 09:00', location: 'aula 10', course_id: courses[0].id},
                           {datetime: '2014-05-03 09:00', location: 'aula 7', course_id: courses[1].id},
                           {datetime: '2014-02-07 09:00', location: 'aula 10', course_id: courses[1].id}])

meetings[0].professors << Professor.where("surname = 'Binetti' or surname = 'Veloce' ")
meetings[1].professors << Professor.where("surname = 'Binetti' or surname = 'Cabotto' ")
meetings[2].professors << Professor.where("surname = 'Amaldo' or surname = 'Veloce' ")
meetings[3].professors << Professor.where("surname = 'Origa' or surname = 'Veloce' or surname = 'Cabotto'")

